CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE match
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    round_id        INTEGER                                  NOT NULL,
    participant1_id INTEGER,
    participant2_id INTEGER,
    score1          INTEGER                                  NOT NULL,
    score2          INTEGER                                  NOT NULL,
    winner_id       INTEGER,
    status          VARCHAR(255)                             NOT NULL,
    order_index     INTEGER                                  NOT NULL,
    scheduled_date  date,
    CONSTRAINT pk_match PRIMARY KEY (id)
);

CREATE TABLE participant
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tournament_id INTEGER                                  NOT NULL,
    user_id       INTEGER,
    team_id       INTEGER,
    CONSTRAINT pk_participant PRIMARY KEY (id)
);

CREATE TABLE phase
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type          VARCHAR(255)                             NOT NULL,
    order_index   INTEGER                                  NOT NULL,
    tournament_id INTEGER                                  NOT NULL,
    CONSTRAINT pk_phase PRIMARY KEY (id)
);

CREATE TABLE register_team
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_id       INTEGER                                  NOT NULL,
    tournament_id INTEGER                                  NOT NULL,
    register_date TIMESTAMP(6) WITHOUT TIME ZONE           NOT NULL,
    status        VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_register_team PRIMARY KEY (id)
);

CREATE TABLE register_user
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       INTEGER                                  NOT NULL,
    tournament_id INTEGER                                  NOT NULL,
    register_date TIMESTAMP(6) WITHOUT TIME ZONE           NOT NULL,
    status        VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_register_user PRIMARY KEY (id)
);

CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE TABLE role_
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_role_ PRIMARY KEY (id)
);

CREATE TABLE round
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type        VARCHAR(255)                             NOT NULL,
    order_index INTEGER                                  NOT NULL,
    phase_id    INTEGER                                  NOT NULL,
    CONSTRAINT pk_round PRIMARY KEY (id)
);

CREATE TABLE team
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at     TIMESTAMP(6) WITHOUT TIME ZONE,
    name           VARCHAR(50)                              NOT NULL,
    team_size      INTEGER                                  NOT NULL,
    number_of_wins INTEGER                                  NOT NULL,
    captain_id     INTEGER                                  NOT NULL,
    CONSTRAINT pk_team PRIMARY KEY (id)
);

CREATE TABLE team_member
(
    team_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    CONSTRAINT pk_team_member PRIMARY KEY (team_id, user_id)
);

CREATE TABLE tournament
(
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at              TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at              TIMESTAMP(6) WITHOUT TIME ZONE,
    name                    VARCHAR(255)                             NOT NULL,
    description             VARCHAR(255)                             NOT NULL,
    max_participants        INTEGER                                  NOT NULL,
    format                  VARCHAR(255)                             NOT NULL,
    status                  VARCHAR(255)                             NOT NULL,
    participant_type        VARCHAR(255),
    start_date              date                                     NOT NULL,
    end_date                date                                     NOT NULL,
    registration_start_date date                                     NOT NULL,
    registration_end_date   date                                     NOT NULL,
    organizer_id            INTEGER                                  NOT NULL,
    CONSTRAINT pk_tournament PRIMARY KEY (id)
);

CREATE TABLE user_
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    username   VARCHAR(255)                             NOT NULL,
    email      VARCHAR(255)                             NOT NULL,
    password   VARCHAR(255)                             NOT NULL,
    role_id    INTEGER,
    CONSTRAINT pk_user_ PRIMARY KEY (id)
);

ALTER TABLE participant
    ADD CONSTRAINT uc_4c4fc2e1b253c5e6ad5172f58 UNIQUE (tournament_id, user_id);

ALTER TABLE participant
    ADD CONSTRAINT uc_6d8cd91739cdd0dd0897f20e2 UNIQUE (tournament_id, team_id);

ALTER TABLE register_team
    ADD CONSTRAINT uc_bb34ed343316c43e8a904709a UNIQUE (team_id, tournament_id);

ALTER TABLE register_user
    ADD CONSTRAINT uc_f17b3109a8ac170ae6288d121 UNIQUE (user_id, tournament_id);

ALTER TABLE role_
    ADD CONSTRAINT uc_role__name UNIQUE (name);

ALTER TABLE team
    ADD CONSTRAINT uc_team_name UNIQUE (name);

ALTER TABLE user_
    ADD CONSTRAINT uc_user__email UNIQUE (email);

ALTER TABLE user_
    ADD CONSTRAINT uc_user__username UNIQUE (username);

ALTER TABLE team_member
    ADD CONSTRAINT uk_team_member_pair UNIQUE (team_id, user_id);

ALTER TABLE match
    ADD CONSTRAINT FK_MATCH_ON_PARTICIPANT1 FOREIGN KEY (participant1_id) REFERENCES participant (id);

ALTER TABLE match
    ADD CONSTRAINT FK_MATCH_ON_PARTICIPANT2 FOREIGN KEY (participant2_id) REFERENCES participant (id);

ALTER TABLE match
    ADD CONSTRAINT FK_MATCH_ON_ROUND FOREIGN KEY (round_id) REFERENCES round (id);

ALTER TABLE match
    ADD CONSTRAINT FK_MATCH_ON_WINNER FOREIGN KEY (winner_id) REFERENCES participant (id);

ALTER TABLE participant
    ADD CONSTRAINT FK_PARTICIPANT_ON_TEAM FOREIGN KEY (team_id) REFERENCES team (id);

ALTER TABLE participant
    ADD CONSTRAINT FK_PARTICIPANT_ON_TOURNAMENT FOREIGN KEY (tournament_id) REFERENCES tournament (id);

ALTER TABLE participant
    ADD CONSTRAINT FK_PARTICIPANT_ON_USER FOREIGN KEY (user_id) REFERENCES user_ (id);

ALTER TABLE phase
    ADD CONSTRAINT FK_PHASE_ON_TOURNAMENT FOREIGN KEY (tournament_id) REFERENCES tournament (id);

ALTER TABLE register_team
    ADD CONSTRAINT FK_REGISTER_TEAM_ON_TEAM FOREIGN KEY (team_id) REFERENCES team (id);

ALTER TABLE register_team
    ADD CONSTRAINT FK_REGISTER_TEAM_ON_TOURNAMENT FOREIGN KEY (tournament_id) REFERENCES tournament (id);

ALTER TABLE register_user
    ADD CONSTRAINT FK_REGISTER_USER_ON_TOURNAMENT FOREIGN KEY (tournament_id) REFERENCES tournament (id);

ALTER TABLE register_user
    ADD CONSTRAINT FK_REGISTER_USER_ON_USER FOREIGN KEY (user_id) REFERENCES user_ (id);

ALTER TABLE round
    ADD CONSTRAINT FK_ROUND_ON_PHASE FOREIGN KEY (phase_id) REFERENCES phase (id);

ALTER TABLE team
    ADD CONSTRAINT FK_TEAM_ON_CAPTAIN FOREIGN KEY (captain_id) REFERENCES user_ (id);

ALTER TABLE tournament
    ADD CONSTRAINT FK_TOURNAMENT_ON_ORGANIZER FOREIGN KEY (organizer_id) REFERENCES user_ (id);

ALTER TABLE user_
    ADD CONSTRAINT FK_USER__ON_ROLE FOREIGN KEY (role_id) REFERENCES role_ (id);

ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);

ALTER TABLE team_member
    ADD CONSTRAINT fk_teamem_on_team_entity FOREIGN KEY (team_id) REFERENCES team (id);

ALTER TABLE team_member
    ADD CONSTRAINT fk_teamem_on_user_entity FOREIGN KEY (user_id) REFERENCES user_ (id);