CREATE TABLE team_invitation (
                                 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 team_id INTEGER NOT NULL REFERENCES team(id) ON DELETE CASCADE,
                                 player_id INTEGER NOT NULL REFERENCES user_(id) ON DELETE CASCADE,
                                 status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED')),
                                 created_at TIMESTAMP NOT NULL,
                                 updated_at TIMESTAMP NOT NULL,
                                 accepted_at TIMESTAMP
);

CREATE UNIQUE INDEX uk_pending_team_invitation
    ON team_invitation (team_id, player_id) WHERE status = 'PENDING';
CREATE INDEX idx_team_invitation_player ON team_invitation (player_id);

CREATE TABLE notification (
                              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              recipient_id INTEGER NOT NULL REFERENCES user_(id) ON DELETE CASCADE,
                              type VARCHAR(255) NOT NULL CHECK (type IN ('MEMBER_REMOVED', 'MEMBER_LEFT')),
                              team_id INTEGER,
                              message VARCHAR(1000) NOT NULL,
                              created_at TIMESTAMP NOT NULL,
                              updated_at TIMESTAMP NOT NULL,
                              read_at TIMESTAMP
);
CREATE INDEX idx_notification_recipient ON notification (recipient_id, created_at DESC, id DESC);

ALTER TABLE user_ ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE team ALTER COLUMN captain_id DROP NOT NULL;

CREATE TABLE team_join_request (
                                   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   team_id INTEGER NOT NULL REFERENCES team(id) ON DELETE CASCADE,
                                   player_id INTEGER NOT NULL REFERENCES user_(id) ON DELETE CASCADE,
                                   status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED')),
                                   created_at TIMESTAMP NOT NULL,
                                   updated_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uk_pending_team_join_request
    ON team_join_request (team_id, player_id) WHERE status = 'PENDING';
CREATE INDEX idx_team_join_request_player ON team_join_request (player_id);
CREATE INDEX idx_team_join_request_team ON team_join_request (team_id);

ALTER TABLE user_ ADD COLUMN token_version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE team ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;